### ISSUE TITLE
error: conflicting types for 'MakeTag'

### ISSUE THREAD

**Issue by ryandesign** [protocolbuffers/protobuf#7665]
**What version of protobuf and what language are you using?**
Version: 3.12.3
Language: cpp

**What operating system (Linux, Windows, ...) and version?** Mac OS X 10.7.5

**What runtime / compiler are you using (e.g., python version or gcc version)** Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)

**What did you do?**
1. install protobuf-cpp 3.12.3
2. build protobuf-c 1.3.3

**What did you expect to see**
successful build

**What did you see instead?**
[This build error](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/24479/steps/install-port/logs/stdio):
```
/opt/local/include/google/protobuf/wire_format_lite.h:784:41: error: conflicting types for 'MakeTag'
constexpr inline uint32 WireFormatLite::MakeTag(int field_number,
                                        ^
/opt/local/include/google/protobuf/wire_format_lite.h:168:27: note: previous declaration is here
  constexpr static uint32 MakeTag(int field_number, WireType type);
                          ^
```

**Anything else we should know about your project / environment**
It builds fine on the newer OS X 10.8 and later. It also builds fine on the older Mac OS X 10.6 when using clang 9 installed using MacPorts. Maybe using a newer clang would help on OS X 10.7 as well, however shouldn't the code be changed so that the types aren't conflicting?

**Comment by elharo** [comment]
I don't think we can support Mac OS 10.7 from 2011.
