### PR TITLE
Make abseil a public dependency of libprotobuf

### PR DESCRIPTION
**Pull request by haraldF**
descriptor.h includes abseil's mutex.h directly, thus abseil is not a
private dependency any more but must be included by every user of
libprotobuf.

### CODE REVIEW

**Comment by haraldF** [comment]
Note - change 701dd83594c5d979481bc36ac58efea670a929ba makes abseil a public dependency of `libprotobuf` by including an abseil header directly in an exported header file. If this wasn't intentional, please revert that change.

Otherwise, abseil must be declared as public dependency, otherwise, `cmake` builds will complain that `absl/synchronization/mutex.h` cannot be found.

**Comment by perezd** [comment]
Thanks for this, we do intend for this to be public and required in our next major release:
https://developers.google.com/protocol-buffers/docs/news/2022-08-03#abseil-dep

File: cmake/libprotobuf.cmake [hunk 1]
```diff
@@ -26,7 +26,7 @@ if(${CMAKE_SYSTEM_NAME} STREQUAL "Android")
   target_link_libraries(libprotobuf PRIVATE log)
 endif()
 target_include_directories(libprotobuf PUBLIC ${protobuf_SOURCE_DIR}/src)
-target_link_libraries(libprotobuf PRIVATE ${protobuf_ABSL_USED_TARGETS})
+target_link_libraries(libprotobuf PUBLIC ${protobuf_ABSL_USED_TARGETS})
```
Comment (mkruskal-google) [inline cmake/libprotobuf.cmake:29]: For consistency, I think we should make all of these public or none of them.  Notably, there's the target_include_directories in the line below, and then all of our other binaries that declare a dependency on Abseil

**Comment by mkruskal-google** [comment]
Can you explain a little more how making it a private dependency breaks you?  When I decided to make it private it seemed like a more conservative first-step, since I assumed anyone using absl directly would declare their own dependency anyway and not need ours.

**Comment by haraldF** [comment]
> Can you explain a little more how making it a private dependency breaks you? 

Thanks for the quick reply :)

I link to `protobuf::libprotobuf` and include a public header from the lib, e.g. . `protobuf/descriptor.h`. I'll immediately get a compilation error because `"absl/synchronization/mutex.h"` cannot be found. Since abseil is a private dependency, CMake doesn't add the abseil include directory to my search path, although it's now required by anyone including protobuf headers.

To reproduce, you can use this little CMake script:

```make
include(FetchContent)

FetchContent_Declare(
  Protobuf
  GIT_REPOSITORY https://github.com/protocolbuffers/protobuf.git
  GIT_TAG        ad55f52fdb4557953593cd096b903b0347b02f25 # or any other SHA close to HEAD
  OVERRIDE_FIND_PACKAGE
)
set(protobuf_BUILD_TESTS OFF CACHE INTERNAL "")
FetchContent_MakeAvailable(Protobuf)
```

(Note - requires CMake 3.24 or higher)

Then create a dummy project, link to `protobuf::libprotobuf` and include descriptor.h in the dummy.cpp:

```cmake
find_package(Protobuf REQUIRED) 
add_executable(dummy dummy.cpp)
target_link_libraries(dummy protobuf::libprotobuf)
```

You should get an immediate compilation error

After making abseil a PUBLIC dependency, CMake understands that it also must add the abseil include dir to projects consuming protobuf, thus the compiler error disappears.

File: cmake/libprotobuf.cmake (hunk 1 above)
Comment (mkruskal-google) [reply cmake/libprotobuf.cmake:29]: Define "legacy" CMake?  We support everything down to 3.5, so we're currently fairly constrained on what we can modernize

**Comment by mkruskal-google** [comment]
Ah that makes sense, thanks for the clarification!  When I first rolled this out I tested it against a dummy CMake project, but at the time we weren't actually using Abseil anywhere so I wouldn't have hit this issue.  Given our rapidly increasing use of Abseil I think a public dependency makes sense

File: cmake/libprotobuf.cmake (hunk 1 above)
Comment (haraldF) [reply cmake/libprotobuf.cmake:29]: `target_include_directories` and scoped projects were introduced during the 2.x series, so we're fairly safe here.

Comment (mkruskal-google) [reply cmake/libprotobuf.cmake:29]: ok, as long as it works with 3.10+ I'm fine cleaning up and modernizing this code :). Note, we also unfortunately have some test environments still using 3.6.

**Review by mkruskal-google — CHANGES_REQUESTED** [review]
This lgtm, but let's update all the other private absl dependencies too

File: cmake/libprotobuf.cmake [hunk 2]
```diff
@@ -26,8 +26,8 @@ if(${CMAKE_SYSTEM_NAME} STREQUAL "Android")
   target_link_libraries(libprotobuf PRIVATE log)
 endif()
 target_include_directories(libprotobuf PUBLIC ${protobuf_SOURCE_DIR}/src)
-target_link_libraries(libprotobuf PRIVATE ${protobuf_ABSL_USED_TARGETS})
-target_include_directories(libprotobuf PRIVATE ${ABSL_ROOT_DIR})
+target_link_libraries(libprotobuf PUBLIC ${protobuf_ABSL_USED_TARGETS})
+target_include_directories(libprotobuf PUBLIC ${ABSL_ROOT_DIR})
```
Comment (mkruskal-google) [inline cmake/libprotobuf.cmake:30]: I thought you were going to remove this line?

File: cmake/libprotobuf.cmake [hunk 3]
```diff
@@ -26,8 +26,8 @@ if(${CMAKE_SYSTEM_NAME} STREQUAL "Android")
   target_link_libraries(libprotobuf PRIVATE log)
 endif()
 target_include_directories(libprotobuf PUBLIC ${protobuf_SOURCE_DIR}/src)
-target_link_libraries(libprotobuf PRIVATE ${protobuf_ABSL_USED_TARGETS})
-target_include_directories(libprotobuf PRIVATE ${ABSL_ROOT_DIR})
+target_link_libraries(libprotobuf PUBLIC ${protobuf_ABSL_USED_TARGETS})
```
Comment (mkruskal-google) [inline cmake/libprotobuf.cmake:29]: Can you update the other cmake files while you're at it?  e.g. libprotoc, protoc, libprotobuf-lite, conformance

Comment (haraldF) [reply cmake/libprotobuf.cmake:29]: Done :)

**Review by mkruskal-google — APPROVED** [review]
