### ISSUE TITLE
error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead

### ISSUE THREAD

**Issue by dpservis** [protocolbuffers/protobuf#23221]
**What version of protobuf and what language are you using?**
Version: head, commit hash 623e36daecc4d7bfcb7954774ecbe5c04e60806c
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows
**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 22
**What did you do?**
1. Generate code
2. Compile code
3. Getting lots of C4996

**What did you expect to see**
Code compiling
**What did you see instead?**
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\repeated_ptr_field.h(1017,25): error C4996: 'google::protobuf::RepeatedPtrField<shipload::Point3D>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\map_field.h(433,62): error C4996: 'google::protobuf::RepeatedPtrField<google::protobuf::Message>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\repeated_ptr_field.h(1017,25): error C4996: 'google::protobuf::RepeatedPtrField<shipload::Point2D>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\map_field.h(433,62): error C4996: 'google::protobuf::RepeatedPtrField<google::protobuf::Message>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\repeated_ptr_field.h(1017,25): error C4996: 'google::protobuf::RepeatedPtrField<shipload::Hold>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(437,19): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
google\protobuf\arena.h(433,25): error C4996: 'google::protobuf::RepeatedPtrField<std::string>::RepeatedPtrField': Use Arena::Create<RepeatedPtrField<...>>(Arena*) instead
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
Compiled with Debug

**Comment by dpservis** [comment]
With v32.0 I do not get these errors

**Comment by esrauchg** [comment]
The error is because you opted into deprecated warning as error. We try to keep warning clean but can't in general, so opting into more warnings-as-errors can have these kind of symptoms. 

If it is fixed in 32.0 I think this is considered fixed overall. Thanks!

**Comment by dpservis** [comment]
Hi, it works in v32.0 but not the head
