### ISSUE TITLE
Compilation failure on HPPA

### ISSUE THREAD

**Issue by Arfrever** [protocolbuffers/protobuf#7682]
Protobuf 3.12.2 fails to compile on HPPA.
This error does not occur on x86_32, x86_64.
Original report: https://bugs.gentoo.org/731002

```
/bin/sh ../libtool  --tag=CXX   --mode=compile hppa2.0-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I/var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src -I..   -DGOOGLE_PROTOBUF_NO_RTTI -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare  -mschedule=8000 -march=2.0 -ggdb -Wall -O2 -pipe -c -o google/protobuf/struct.pb.lo /var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/struct.pb.cc
libtool: compile:  hppa2.0-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I/var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src -I.. -DGOOGLE_PROTOBUF_NO_RTTI -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -mschedule=8000 -march=2.0 -ggdb -Wall -O2 -pipe -c /var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/struct.pb.cc  -fPIC -DPIC -o google/protobuf/.libs/struct.pb.o
In file included from /var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/struct.pb.h:24,
                 from /var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/struct.pb.cc:4:
/var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/arena.h: In instantiation of ‘void* google::protobuf::Arena::AllocateInternal(bool) [with T = google::protobuf::Struct]’:
/var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/arena.h:609:28:   required from ‘T* google::protobuf::Arena::DoCreateMessage(Args&& ...) [with T = google::protobuf::Struct; Args = {}]’
/var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/arena.h:503:39:   required from ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = google::protobuf::Struct]’
/var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/struct.pb.cc:1097:77:   required from here
/var/tmp/portage/dev-libs/protobuf-3.12.2/work/protobuf-3.12.2/src/google/protobuf/arena.h:531:30: error: static assertion failed: T is overaligned, see b/151247138
  531 |     static_assert(alignof(T) <= 8, "T is overaligned, see b/151247138");
      |                   ~~~~~~~~~~~^~~~
make[2]: *** [Makefile:4082: google/protobuf/struct.pb.lo] Error 1
```

Failing `static_assert(alignof(T) <= 8, "T is overaligned, see b/151247138")` was introduced in commit b99994d994e399174fe688a5efbcb6d91f36952a.

**Comment by Arfrever** [comment]
This `static_assert(alignof(T) <= 8, "T is overaligned, see b/151247138")` line in `src/google/protobuf/arena.h` was deleted in commit b70695dd68488e0a9bc847de69dadc6b47e251e9.
