### ISSUE TITLE
error C2127: illegal initialization of 'constinit' entity with a non-constant expression

### ISSUE THREAD

**Issue by chronoxor** [protocolbuffers/protobuf#9698]
**What version of protobuf and what language are you using?**
Version: master
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2022

**What did you do?**

`repeated Order orders` protobuf definition generates compile error in Visual Studio 2022
```
trade.pb.cc(53,111): error C2127: 'Trade::protobuf::_Account_default_instance_': illegal initialization of 'constinit' entity with a non-constant expression
```

for the following .proto file:
```
syntax = "proto3";
package Trade.protobuf;

message Order
{
    int32 id = 1;
    string symbol = 2;
}

message Account
{
    int32 id = 1;
    string name = 2;
    repeated Order orders = 3;
}
```

**Comment by jorgbrown** [comment]
FWIW, I copied the generated code, or at least, enough of it to allow _Account_default_instance_ to be defined, and was unable to reproduce this error.  https://godbolt.org/z/j97bvjq44

**Comment by chronoxor** [comment]
Here is a reproduced issue in godbolt - https://godbolt.org/z/44bsG5733

**Comment by ReeceSX** [comment]
1>C:\Users\Admin\Desktop\Aurora2\Scriptability\Vendor\protobuf\src\google\protobuf\api.pb.cc(42,107): error C2127: 'google::protobuf::_Api_default_instance_': illegal initialization of 'constinit' entity with a non-constant expression
`PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ApiDefaultTypeInternal _Api_default_instance_;`

1>C:\Users\Admin\Desktop\Aurora2\Scriptability\Vendor\protobuf\src\google\protobuf\api.pb.cc(61,110): error C2127: 'google::protobuf::_Method_default_instance_': illegal initialization of 'constinit' entity with a non-constant expression
1>generator.cc
`
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MethodDefaultTypeInternal _Method_default_instance_;`

_fun_

**Comment by jgcodes2020** [comment]
The bug seems like it would be caused by #10159.

**Comment by huysuper** [comment]
The release 3.2x.x have these issues
I have tested with [v3.19.4](https://github.com/protocolbuffers/protobuf/tree/v3.19.4) it works well
When I trace the change of src\google\protobuf\port_def.inc and I see the [commit](https://github.com/protocolbuffers/protobuf/commit/ab4585a6956675ce14a1cba5d321fde980bbf12b#diff-c6c960709f2bebcb680ec27d5b8c61777bcfa7081e00229e22b0fe9fc3226ee5) overrides this pull request [#8690](https://github.com/protocolbuffers/protobuf/pull/8690)
This is the cause we can not build on Visual Studio 2019 Update 16.10
![image](https://user-images.githubusercontent.com/30212884/177937745-41ef66ca-140c-4232-955a-2bcef636813c.png)
