### ISSUE TITLE
C#: generated code contains C# 7 features

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/protobuf#5676]
Release blocker for v3.7.0

https://github.com/protocolbuffers/protobuf/pull/5183/files has introduced C# features to the generated code:

The `ref` is a C# 7 construct. https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#ref-locals-and-returns
```
if (!pb::UnknownFieldSet.MergeFieldFrom(ref _unknownFields, input)) {
        return;
}
```

Protobuf generated code needs to be compatible with older .NET and C# versions (with even older versions that the runtime itself, because the runtime is not built by users), so C# 7 is not acceptable.

The error you get with older C# compiler
```
Math.cs(747,57): error CS1615: Argument 1 may not be passed with the 'ref' keyword [T:\src\github\grpc\workspace_csharp_windows_dbg_native\src\csharp\Grpc.Examples\Grpc.Examples.csproj]
```

**Comment by acozzette** [comment]
@ObsidianMinor Do you think you could help fix this? It looks like this was introduced in 6f73c509365fcb9. I don't really know C# but is this `ref` keyword perhaps just an optimization that we could remove for now?

**Comment by jtattermusch** [comment]
@ObsidianMinor  what was the original reason for adding a new MergeFieldFrom overload?

**Comment by jtattermusch** [comment]
CC @anandolee

**Comment by ObsidianMinor** [comment]
The original reason the overload was added was that I needed a way to communicate with the class's merge method about whether an end tag was reached. 

Originally I made it so reaching the end tag for the current group would return zero when reading a tag from the input, but after review it was decided I should do it another way and Java's implementation was brought up as an example. The closest thing I had for reference was that Java implementation so I wrote it based on that. 

The overload returns a bool indicating if an end tag was reached and takes the unknown field set as a reference to assign it where originally the generated code would.

**Comment by TeBoring** [comment]
I remember we required non-C#-7 in our test setup. Why this still happens?

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/commit/db0a9e0b962084cdb7f51a31d9ed670f54189981#diff-a20d785dbacb8f41a3b7392aa7d03b78

**Comment by lostindark** [comment]
To clarify, the `ref` keyword is not a C#7 feature, not confused it with `Ref locals and returns`. The problem here is not related to `Ref locals and returns`, so force <LangVersion>6</LangVersion> won't detect this issue.

**Comment by TeBoring** [comment]
Pending on #5708

**Comment by TeBoring** [comment]
Is there anything needed to close this issue?
