### ISSUE TITLE
min/max namespace collision on Windows

### ISSUE THREAD

**Issue by tawmoto** [protocolbuffers/protobuf#9256]
Hi,

I am using Windows 10, protobuf in C++.
When I updated to 3.19.1, my code does not compile anymore.

```
\protobuf-src\include\google/protobuf/stubs/stl_util.h(60,21): error C2589: '(': illegal token on right side of '::' 
\protobuf-src\include\google/protobuf/stubs/stl_util.h(60): error C2144: syntax error: 'unknown-type' should be preceded by ')' 
```

This is caused by the line
https://github.com/protocolbuffers/protobuf/blob/v3.19.1/src/google/protobuf/stubs/stl_util.h#L60

And a classical min/max problem on Windows
https://stackoverflow.com/questions/13416418/define-nominmax-using-stdmin-max

A solution for me would be to `undef max` before including `protobuf`, I tested, it works, but it's quite hackish.
I think protobuf should protect itself from such uses and should not break existing builds when the users update to a newer version. 

Thank you

**Comment by acozzette** [comment]
The way we usually work around this is to include `<google/protobuf/port_def.inc>` as the last include at the top of the file and then include `<google/protobuf/port_undef.inc>` at the end of the file. `port_def.inc` will `undef` the `max` macro and then `port_undef.inc` restores it. If you send me a pull request to do this in `stl_util.h` then I would be happy to merge it.

**Comment by tawmoto** [comment]
Hmm, it seems that there is already an open task for this and a PR
https://github.com/protocolbuffers/protobuf/pull/9273

**Comment by elharo** [comment]
should be fixed by #9273
