### ISSUE TITLE
Unit tests fail to build on GCC 5.4

### ISSUE THREAD

**Issue by thejray** [protocolbuffers/protobuf#7095]
**What version of protobuf and what language are you using?**
Version: v3.11.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux Debian Jesse

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC 5.4.0

**What did you do?**
1. Create a docker container: `docker run --rm -it gcc:5.4 /bin/bash`
2. Install and run protobuf
```
mkdir -p /protobuf
cd /protobuf     
curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protobuf-all-3.11.2.tar.gz | tar xzv --strip-components=1
./configure
make
make check
```
**What did you expect to see**
`make check` should pass, and it does not

**What did you see instead?**
error messages like:
```
google/protobuf/text_format_unittest.cc:1205:20: error: expected unqualified-id before '(' token
   EXPECT_TRUE(std::isnan(message.repeated_double(11)));
....
google/protobuf/text_format_unittest.cc:1206:20: error: expected unqualified-id before '(' token
   EXPECT_TRUE(std::isnan(message.repeated_double(12)));
```

**Potential solution**

This can be fixed by changing [this include](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/text_format_unittest.cc#L37) from `math.h` to `cmath`.  A similar change was made between 3.10.0 and 3.11.2 in [the corresponding source file](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/text_format.cc#L42).

I am submitting this as an issue instead of a PR because I don't want to go through the hoops of a CLA for a one-line PR.

**Comment by elharo** [comment]
5.4 is too old a version for us to support.
