### ISSUE TITLE
Regression: Latest protobuf version doesn't work with unittest.mock. Older versions work.

### ISSUE THREAD

**Issue by BenWhetton** [protocolbuffers/protobuf#12222]
I have created a repo containing all of the files and a couple of scripts to reproduce this [here](https://github.com/BenWhetton/protobuf-mocks). You'll see that `run.py` in v3.19.4 works whereas the one in v4.22.1 doesn't

**What version of protobuf and what language are you using?**
Version: v4.22.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8.10 (but also seen on 3.9.5, 3.9.9)

**What did you do?**
Mock at protobuf class using `unittest.mock.Mock` and try to access
```
a = Mock(MessageType)
a.<someattribute>
```

**What did you expect to see**
The attribute should be present on the mock.

**What did you see instead?**
AttributeError: Mock object has no attribute 'someattribute'

**Comment by billworks** [comment]
This also happens for me when upgrading protobuf from v3.20.3 to v4.21.12. So it must be something introduced in v4.21 that cause this regression.

**Comment by haberman** [comment]
Sorry for the lack of response on this issue.

This appears to arise because Protobuf 4.21+ now implements field access via `msg.__getatttr__` rather than using descriptors (`msg.field.__get__`) like the previous implementation did.

The new design saves memory by creating fewer objects, but one side effect is that it can no longer be mocked through `unittest.mock`.

We don't generally recommend that people mock protobuf objects. Protos are dumb data containers, not objects with behavior. It's best to just treat them as dumb containers.

**Comment by BenWhetton** [comment]
Thanks for the info.

I think this design decision might have had another very unergonomic side-effect: I think since this change was made, message fields can no longer be inspected in the debugger (at least in pycharm), the only way to see what a field contains is to execute `msg.some_field.some_nested_field` etc., and auto-complete no longer works, so we have to remember/copy-paste/cross-reference the names of all nested fields. In pdb, running `dir(msg)` no longer includes the field names, so I doubt this issue is PyCharm specific.

This is very very painful compared to before. I imagine your internal users probably have tooling to help with this? Is there any way that it can be improved for those of us who are on the outside?

Perhaps I should open another ticket for that issue?

**Comment by haberman** [comment]
Is pycharm able to use `.pyi` files to discover attribute names?

Generally our strategy has been to optimize the core library and generated code primarily for performance (CPU, memory, etc) and rely on the `.pyi` files to give good DevX (autocomplete, etc).

**Comment by BenWhetton** [comment]
> Is pycharm able to use `.pyi` files to discover attribute names?

I imagine it could, and I will probably open a request for this, but there will inevitably be a delay in this kind of change making it into users hands, assuming it gets prioritised.

> Generally our strategy has been to optimize the core library and generated code primarily for performance (CPU, memory, etc) and rely on the `.pyi` files to give good DevX (autocomplete, etc).

I see the logic behind that; however, there are trade-offs involved, and different stakeholders might choose different trade-offs in cases like this. Python is a language that is typically chosen for being easy to use and learn. Users accept that they are not getting C performance when they pick the language, and that features generally are not cost-free. I obviously don't know what the exact rationale was behind this choice, and how much of a performance benefit it provides, but I doubt it's a trade-off I would choose without having access to tooling which maintains a good developer experience. In this particular case, it feels to me like google's incentives (at least 7/11 of the listed members of the protocol buffers project) may be a bit misaligned with a large proportion of the external users.

Do you/have you considered informing/collaborating with tooling providers to ensure that they can adapt to significant changes like this to avoid deteriorating the developer experience of many external users?

**Comment by haberman** [comment]
Optimization of the core library is in response to user feedback. Some users process large payloads in Python, and they expect to get good performance even when querying large datasets.

We use SemVer so that users are in control of when they are exposed to breaking changes like this. This change occurred between 3.x and 4.x; users who are affected can stay on 3.x until the tooling catches up wrt. `.pyi` support.
