### ISSUE TITLE
Protobuf-32.1 fails to compile with Linux/aarch64 gcc-15.2.0

### ISSUE THREAD

**Issue by kongen** [protocolbuffers/protobuf#23740]
CFLAGS: -g -march=armv8-a+crc -Wno-error=array-bounds -Os
CPPFLAGS: -g -march=armv8-a+crc -Wno-error=array-bounds -Os
CXXFLAGS: -g -march=armv8-a+crc -Wno-error=array-bounds -Os
LDFLAGS:  -Wno-error=array-bounds
GCC: 15.2.0
Platform: AARCH64 / ARMv8-a
Build system: GNU make 4.3

/home/shm/src/gerrit-02/axon_edge_sdk/build/sources/protobuf-32.0/src/google/protobuf/port.h:800:10: error: '__builtin_arm_crc32cd' was not declared in this scope; did you mean '__builtin_aarch64_crc32cx'?
  800 |   return __builtin_arm_crc32cd(crc, v);
      |          ^~~~~~~~~~~~~~~~~~~~~
      |          __builtin_aarch64_crc32cx

I think the compiler is right - this should have been __builtin_aarch64_crc32cx()

**Comment by jngrb** [comment]
In case someone stumbles across this:

- introduced with #22081 in Protobuf v32 / v6.32
- solved with #23164 / #23194 in Protobuf v33 / v6.33
