### ISSUE TITLE
PROTOBUF_EXPORT alignas(n) doesn't compile with GCC 7

### ISSUE THREAD

**Issue by utkarshayachit** [protocolbuffers/protobuf#7024]
**What version of protobuf and what language are you using?**
Version: v3.11.2
Language: C++

**What operating system (Linux, Windows, ...) and version?**

Linux

**What runtime / compiler are you using (e.g., python version or gcc version)**

GCC 7.4.0

**What did you do?**
Attempt to build core libraries.

**What did you expect to see**

No compile error.

**What did you see instead?**

```
.../src/google/protobuf/arena.h:251:23: error: expected identifier before ‘alignas’
 class PROTOBUF_EXPORT alignas(8) Arena final {
```

Introduced in 09cab821a96c52b7b3482bd993177a33098012a8.

**Comment by utkarshayachit** [comment]
It does work with Clang, but not GCC (even 9). Godbolt link for a small example: https://godbolt.org/z/wwty7Y

**Comment by dje29** [comment]
Hello @utkarshayachit 
I was having similar problem in my project with version v3.11.1 but seems there is now a fix for that.
See: [32caf511c8](https://github.com/protocolbuffers/protobuf/commit/32caf511c8)

**Comment by elharo** [comment]
fixed
