### ISSUE TITLE
Protobuf fails to compile on Ubuntu 22.04 when -Dprotobuf_BUILD_SHARED_LIBS=ON flag set.

### ISSUE THREAD

**Issue by BDokas** [protocolbuffers/protobuf#10833]
**What version of protobuf and what language are you using?**
Version: v3.21.4
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, Ubuntu 22.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
cmake 

**What did you do?**
1. Run `git clone https://github.com/protocolbuffers/protobuf.git`
2. Run `cd protobuf`
3. Run `git submodule update --init --recursive`
4. Run `cmake -Dprotobuf_BUILD_SHARED_LIBS=ON .`
5. Run `cmake --build . --parallel 10`

**What did you expect to see**
A successful build with shared objects generated in /usr/local/libs after installation.

**What did you see instead?**
```
/usr/bin/ld: libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::erase(google::protobuf::internal::RepeatedPtrIterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/protoc.dir/build.make:151: protoc-3.21.4.0] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:889: CMakeFiles/protoc.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[protobuf_build_failure.txt](https://github.com/protocolbuffers/protobuf/files/9882547/protobuf_build_failure.txt)

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by enum-class** [comment]
I think your problem is similar to this, please check it :
https://github.com/protocolbuffers/protobuf/issues/10828

**Comment by enum-class** [comment]
The problem is about extern template class in repeated_ptr_field.h line 2029.
The trivial way to solve this problem is comment the extern which will impose a lot of burden on compiler and linker.
You can use this method until the problem truly get solved.
I can fix it if nobody mind

**Comment by acozzette** [comment]
I tried this today and wasn't able to reproduce it. Both on main and v21.4, the build succeeded. This was not on Ubuntu but on Debian. Is there anything else that's important to trigger the error?

**Comment by enum-class** [comment]
Hi @acozzette , Today I tried main branch on clean Debian and Ubuntu, still see undefined reference error at the link time of libprotoc.so.

```
googletest.cc:(.text+0x2cf): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::end()'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Add()'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::Arena*)'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~RepeatedPtrField()'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Clear()'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::InternalSwap(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >*)'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::begin()'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::size() const'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::MergeFrom(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(int) const'
libprotoc.so.3.21.4.0: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::erase(google::protobuf::internal::RepeatedPtrIterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>)'
collect2: error: ld returned 1 exit status
CMakeFiles/test_plugin.dir/build.make:192: recipe for target 'test_plugin' failed
make[2]: *** [test_plugin] Error 1
CMakeFiles/Makefile2:1084: recipe for target 'CMakeFiles/test_plugin.dir/all' failed
make[1]: *** [CMakeFiles/test_plugin.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by acozzette** [comment]
I tried this on my laptop and was able to reproduce the error. When I run `nm -C -D libprotobuf.so.3.21.4.0`, I see that the `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string...` symbols are not being exported. It's strange that they do appear when I try this on my workstation, though.

**Comment by acozzette** [comment]
Ok, I think I've figured out what's going on. I suspect it's a behavior difference between Clang and GCC, because on my laptop with GCC I can run `objdump -Ct ./CMakeFiles/libprotobuf.dir/src/google/protobuf/repeated_field.cc.o` and see the symbols listed as `hidden`, whereas on my workstation with Clang they show up without `hidden`.

The Clang behavior is surprising to me, because it's treating the symbols as visible even though we're building with `-fvisibility=hidden`. We do set the visibility to public [here](https://github.com/protocolbuffers/protobuf/blob/2880fef06cb7443ba24dc1264ba9f02115407f2c/src/google/protobuf/repeated_ptr_field.h#L2024), but the compiler currently doesn't have access to that declaration when it's building repeated_field.cc.

So I think the fix is just to make sure the `PROTOBUF_EXPORT_TEMPLATE_DECLARE` declaration from repeated_ptr_field.h is visible before we instantiate the template with `template class PROTOBUF_EXPORT_TEMPLATE_DEFINE RepeatedPtrField<std::string>;`. As long as the compiler sees that declaration (which includes `__attribute__ ((visibility ("default")))`) then it should generate code that correctly marks the symbol as public.

**Comment by acozzette** [comment]
Actually my theory above was slightly wrong: the compiler always has access to the visibility declaration, but it was appearing too late:
```
:In file included from /home/acozzette/src/protobuf/src/google/protobuf/repeated_field.h:61,
                 from /home/acozzette/src/protobuf/src/google/protobuf/implicit_weak_message.h:39,
                 from /home/acozzette/src/protobuf/src/google/protobuf/implicit_weak_message.cc:31:
/home/acozzette/src/protobuf/src/google/protobuf/repeated_ptr_field.h:2025:5: warning: type attributes ignored after type is already defined [-Wattributes]
 2025 |     RepeatedPtrField<std::string>;
```
I think the fix is just to move the `PROTOBUF_EXPORT_TEMPLATE_DECLARE` declaration further up in repeated_ptr_field.h so that it appears *before* we ever instantiate `RepeatedPtrField<std::string>`. I guess GCC ignored the visibility attributes because they appeared too late, but Clang was OK with accepting them anyway.
