### ISSUE TITLE
Ruby library fails to build on FreeBSD 12 (3.7.1 && master)

### ISSUE THREAD

**Issue by adam12** [protocolbuffers/protobuf#6065]
**What version of protobuf and what language are you using?**
Version: master && 3.7.1
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
FreeBSD 12.0-RELEASE

**What runtime / compiler are you using (e.g., python version or gcc version)**
Ruby 2.6.1
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)

**What did you do?**
`gem install google-protobuf -v  3.7.1` OR `rake compile` from `ruby/` path in project.

**What did you expect to see**
Gem successfully installing.

**What did you see instead?**
Gem failed to build due to compiler error. There are many warnings but this is the error that triggers the failure:

```
upb/json/parser.rl:1723:30: error: use of undeclared identifier 'timezone'
  seconds = mktime(&p->tm) - timezone;
```

If I revert 33dd96c23f1595d418fa40a5fc42f786322e2b42 it builds successfully.

**Comment by peikk0** [comment]
Same on FreeBSD 11.2.

**Comment by jsonstro** [comment]
I see this as well on 11.2
