### ISSUE TITLE
v3.7.0: `error: 'PROTOBUF_MIN_PROTOC_VERSION' is not defined`

### ISSUE THREAD

**Issue by scottmin0r** [protocolbuffers/protobuf#5863]
**What version of protobuf and what language are you using?**
Language: C++

I'm trying to update our Bazel codebase from v3.6.1.3 to v3.7.0.

**What operating system (Linux, Windows, ...) and version?**
Linux, Debian variant

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 7.0.1

**What did you do?**
Update protobuf v3.6.1.3 to v3.7.0
`bazel build <some target that relies on proto-generated files>`

**What did you expect to see**
Successful compilation

**What did you see instead?**

```
bazel-out/k8-fastbuild/genfiles/util/task/codes.pb.h:16:15: error: 'PROTOBUF_MIN_PROTOC_VERSION' is not defined, evaluates to 0 [-Werror,-Wundef]
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
              ^
1 error generated.
```

**Anything else we should know about your project / environment**

With protobuf v3.6.1.3, generated headers start with:

```
#ifndef PROTOBUF_INCLUDED_util_2ftask_2fcodes_2eproto
#define PROTOBUF_INCLUDED_util_2ftask_2fcodes_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_util_2ftask_2fcodes_2eproto 
```

With protobuf v3.7.0, generated headers start with:

```
#ifndef PROTOBUF_INCLUDED_util_2ftask_2fcodes_2eproto
#define PROTOBUF_INCLUDED_util_2ftask_2fcodes_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_util_2ftask_2fcodes_2eproto
```

Some observations:
* `#include <google/protobuf/stubs/common.h>` had previously provided `GOOGLE_PROTOBUF_MIN_PROTOC_VERSION`, but this include is removed in the later generated files.
* `#include <google/protobuf/port_def.inc>` is new in 3.7.0; is this supposed to provide `GOOGLE_PROTOBUF_MIN_PROTOC_VERSION`?

In v3.6.1.3:

* [`compiler/cpp/cpp_file.cc`](https://github.com/protocolbuffers/protobuf/blob/66dc42d891a4fc8e9190c524fd67961688a37bbe/src/google/protobuf/compiler/cpp/cpp_file.cc#L1168) emits macro `GOOGLE_PROTOBUF_MIN_PROTOC_VERSION` in preprocessor checks in generated files
* [`stubs/common.h`](https://github.com/protocolbuffers/protobuf/blob/66dc42d891a4fc8e9190c524fd67961688a37bbe/src/google/protobuf/stubs/common.h#L120) defines `GOOGLE_PROTOBUF_MIN_PROTOC_VERSION` for said checks

In v3.7.0:

* [`compiler/cpp/cpp_file.cc`](https://github.com/protocolbuffers/protobuf/blob/582743bf40c5d3639a70f98f183914a2c0cd0680/src/google/protobuf/compiler/cpp/cpp_file.cc#L1217) emits *renamed* macro `PROTOBUF_MIN_PROTOC_VERSION` in preprocessor checks in generated files
* [`stubs/common.h`](https://github.com/protocolbuffers/protobuf/blob/582743bf40c5d3639a70f98f183914a2c0cd0680/src/google/protobuf/stubs/common.h#L100) still sets `GOOGLE_PROTOBUF_MIN_PROTOC_VERSION` (but this header is no longer included; see above)
* No file sets `PROTOBUF_MIN_PROTOC_VERSION` that I can find

Questions:
* How is the `*_MIN_PROTOC_VERSION` macro supposed to work in v3.7.0?
* Did this macro get renamed?
* What header is supposed to define it?

Could there be something wrong with our Bazel configuration that would lead to this?

**Comment by scottmin0r** [comment]
To reproduce:

* Check out 3.7.0 - `git checkout v3.7.0`
* Build `protoc` using bazel: `bazel build //:protoc`
* Create a trivial proto to compile:

   ```
   cat <<EOF > /tmp/p.proto
   syntax = "proto2";

   message Hello {
     optional string world = 1;
   }
   EOF
   ```

* Compile: `bazel-bin/protoc --cpp_out=/tmp/cpp_out /tmp/p.proto --proto_path=/tmp`
* `head -20 /tmp/cpp_out/p.pb.h`:

   ```
   // Generated by the protocol buffer compiler.  DO NOT EDIT!
   // source: p.proto

   #ifndef PROTOBUF_INCLUDED_p_2eproto
   #define PROTOBUF_INCLUDED_p_2eproto

   #include <limits>
   #include <string>

   #include <google/protobuf/port_def.inc>
   #if PROTOBUF_VERSION < 3007000
   #error This file was generated by a newer version of protoc which is
   #error incompatible with your Protocol Buffer headers. Please update
   #error your headers.
   #endif
   #if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
   #error This file was generated by an older version of protoc which is
   #error incompatible with your Protocol Buffer headers. Please
   #error regenerate this file with a newer version of protoc.
   #endif
   ```

* Try to compile: `gcc -c -o /tmp/cpp_out/p.pb.o -isystem src/ -Wundef -Werror`:
   
   ```
   /tmp/cpp_out/p.pb.h:16:15: error: "PROTOBUF_MIN_PROTOC_VERSION" is not defined, evaluates to 0 [-Werror=undef]
   #if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
   cc1plus: all warnings being treated as errors
   ```

**Comment by TeBoring** [comment]
@scottmin0r Please take a look of #5881
