### ISSUE TITLE
Windows CUDA10.2 compile error when update to protobuf 3.20.0

### ISSUE THREAD

**Issue by zhouwei25** [protocolbuffers/protobuf#11902]
When I update protobuf to 3.20.0

It usually compile error:

![infoflow 2023-02-10 18-30-48](https://user-images.githubusercontent.com/52485244/218069471-7f4af635-eb60-49a6-8d3b-c04b20efa1e2.png)

```
d:\paddle\build\third_party\eigen3\src\extern_eigen3\eigen\src/Core/util/Meta.h(572): error C2065: 'T': undeclared identifier
d:\paddle\build\third_party\eigen3\src\extern_eigen3\eigen\src/Core/util/Meta.h(572): note: see reference to class template instantiation 'Eigen::internal::binary_result_of_select<Func,ArgType0,ArgType1,12>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xtr1common(91): note: see reference to class template instantiation 'std::integral_constant<bool,true>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xtr1common(94): note: see reference to class template instantiation 'std::is_same<_Ty1,_Ty1>' being compiled
```

Does anyone has some suggetions? Thanks very much.

**Comment by esorot** [comment]
Additional information is required to further diagnose. Please follow our issue template and reopen if this is still a problem.
