### ISSUE TITLE
lite-test fails to link with -fvisibility=hidden since v25.0

### ISSUE THREAD

**Issue by JamiKettunen** [protocolbuffers/protobuf#14726]
Upgrading the Chimera Linux package from v24.4 to v25.0 (https://github.com/chimera-linux/cports/pull/898) I noticed hidden visibility now breaks compilation: with v24.4 it works fine (LLVM 17.0.4 toolchain) but now it fails to build `lite-test` due to some undefined symbols such as:
```
FAILED: lite-test 
: && /usr/lib/ccache/bin/clang++ -Wformat -Werror=format-security -ftrivial-auto-var-init=zero -fstack-clash-protection -fvisibility=hidden -fsanitize=signed-integer-overflow,integer-divide-by-zero -fsanitize-trap=signed-integer-overflow,integer-divide-by-zero -fno-sanitize-recover -flto=thin -O2 -ffile-prefix-map=/builddir/protobuf-25.0=. -g2 -Wl,-z,pack-relative-relocs -fvisibility=hidden -fsanitize=signed-integer-overflow,integer-divide-by-zero -fsanitize-trap=signed-integer-overflow,integer-divide-by-zero -fno-sanitize-recover -flto=thin CMakeFiles/lite-test.dir/src/google/protobuf/lite_arena_unittest.cc.o CMakeFiles/lite-test.dir/src/google/protobuf/lite_unittest.cc.o CMakeFiles/lite-test.dir/src/google/protobuf/arena_test_util.cc.o CMakeFiles/lite-test.dir/src/google/protobuf/map_lite_test_util.cc.o CMakeFiles/lite-test.dir/src/google/protobuf/test_util_lite.cc.o -o lite-test  -Wl,-rpath,/builddir/protobuf-25.0/build  liblibtest_common_lite.so  libprotobuf-lite.so.25.0.0  /usr/lib/libabsl_die_if_null.so.2308.0.0  /usr/lib/libabsl_flags.so.2308.0.0  /usr/lib/libabsl_log_initialize.so.2308.0.0  /usr/lib/libabsl_statusor.so.2308.0.0  /usr/lib/libabsl_scoped_mock_log.so.2308.0.0  /usr/lib/libgmock_main.so.1.14.0  /usr/lib/libabsl_log_internal_check_op.so.2308.0.0  /usr/lib/libabsl_leak_check.so.2308.0.0  /usr/lib/libabsl_log_internal_conditions.so.2308.0.0  /usr/lib/libabsl_log_internal_message.so.2308.0.0  /usr/lib/libabsl_log_internal_nullguard.so.2308.0.0  /usr/lib/libabsl_examine_stack.so.2308.0.0  /usr/lib/libabsl_log_internal_format.so.2308.0.0  /usr/lib/libabsl_log_internal_proto.so.2308.0.0  /usr/lib/libabsl_flags_internal.so.2308.0.0  /usr/lib/libabsl_flags_marshalling.so.2308.0.0  /usr/lib/libabsl_flags_reflection.so.2308.0.0  /usr/lib/libabsl_flags_config.so.2308.0.0  /usr/lib/libabsl_flags_program_name.so.2308.0.0  /usr/lib/libabsl_flags_private_handle_accessor.so.2308.0.0  /usr/lib/libabsl_flags_commandlineflag.so.2308.0.0  /usr/lib/libabsl_flags_commandlineflag_internal.so.2308.0.0  /usr/lib/libabsl_raw_hash_set.so.2308.0.0  /usr/lib/libabsl_hashtablez_sampler.so.2308.0.0  /usr/lib/libabsl_status.so.2308.0.0  /usr/lib/libabsl_cord.so.2308.0.0  /usr/lib/libabsl_cordz_info.so.2308.0.0  /usr/lib/libabsl_cord_internal.so.2308.0.0  /usr/lib/libabsl_cordz_functions.so.2308.0.0  /usr/lib/libabsl_exponential_biased.so.2308.0.0  /usr/lib/libabsl_cordz_handle.so.2308.0.0  /usr/lib/libabsl_crc_cord_state.so.2308.0.0  /usr/lib/libabsl_crc32c.so.2308.0.0  /usr/lib/libabsl_crc_internal.so.2308.0.0  /usr/lib/libabsl_crc_cpu_detect.so.2308.0.0  /usr/lib/libabsl_str_format_internal.so.2308.0.0  /usr/lib/libabsl_strerror.so.2308.0.0  /usr/lib/libabsl_log_internal_log_sink_set.so.2308.0.0  /usr/lib/libabsl_synchronization.so.2308.0.0  /usr/lib/libabsl_stacktrace.so.2308.0.0  /usr/lib/libabsl_symbolize.so.2308.0.0  /usr/lib/libabsl_debugging_internal.so.2308.0.0  /usr/lib/libabsl_demangle_internal.so.2308.0.0  /usr/lib/libabsl_graphcycles_internal.so.2308.0.0  /usr/lib/libabsl_kernel_timeout_internal.so.2308.0.0  /usr/lib/libabsl_malloc_internal.so.2308.0.0  /usr/lib/libabsl_log_globals.so.2308.0.0  /usr/lib/libabsl_hash.so.2308.0.0  /usr/lib/libabsl_bad_optional_access.so.2308.0.0  /usr/lib/libabsl_bad_variant_access.so.2308.0.0  /usr/lib/libabsl_city.so.2308.0.0  /usr/lib/libabsl_low_level_hash.so.2308.0.0  /usr/lib/libabsl_log_internal_globals.so.2308.0.0  /usr/lib/libabsl_log_sink.so.2308.0.0  /usr/lib/libabsl_log_entry.so.2308.0.0  /usr/lib/libabsl_time.so.2308.0.0  /usr/lib/libabsl_strings.so.2308.0.0  /usr/lib/libabsl_string_view.so.2308.0.0  /usr/lib/libabsl_throw_delegate.so.2308.0.0  /usr/lib/libabsl_strings_internal.so.2308.0.0  /usr/lib/libabsl_base.so.2308.0.0  /usr/lib/libabsl_spinlock_wait.so.2308.0.0  /usr/lib/libabsl_raw_logging_internal.so.2308.0.0  /usr/lib/libabsl_log_severity.so.2308.0.0  /usr/lib/libabsl_int128.so.2308.0.0  /usr/lib/libabsl_civil_time.so.2308.0.0  /usr/lib/libabsl_time_zone.so.2308.0.0  /usr/lib/libgmock.so.1.14.0  /usr/lib/libgtest.so.1.14.0 && :
ld: error: undefined symbol: protobuf_unittest::ForeignEnumLite_Name(protobuf_unittest::ForeignEnumLite)
>>> referenced by lite_unittest.cc:1155 (./build/../src/google/protobuf/lite_unittest.cc:1155)
>>>               lto.tmp:(google::protobuf::(anonymous namespace)::LiteTest_EnumValueToName_Test<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::TestBody())
>>> referenced by lite_unittest.cc:1157 (./build/../src/google/protobuf/lite_unittest.cc:1157)
>>>               lto.tmp:(google::protobuf::(anonymous namespace)::LiteTest_EnumValueToName_Test<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::TestBody())
>>> referenced by lite_unittest.cc:1159 (./build/../src/google/protobuf/lite_unittest.cc:1159)
>>>               lto.tmp:(google::protobuf::(anonymous namespace)::LiteTest_EnumValueToName_Test<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::TestBody())
>>> referenced 7 more times
```
Full build log: https://paste.c-net.org/padqg8jntmf5

I did try to `git bisect` to at least get a commit causing it but it seems the git history on this repo was force-pushed and broken between releases additionally with the commits I got mostly just failing to build `protoc-24.0.0` due to:
```
ld: error: undefined reference due to --no-allow-shlib-undefined: google::protobuf::internal::InternalOutOfLineDeleteMessageLite(google::protobuf::MessageLite*)
```

**Comment by JamiKettunen** [comment]
The following makes it at least build with `-fvisibility=hidden` but I'm unsure the lite library will work as expected so I'll refrain from shipping it even for the distro packaging:
```diff
--- a/cmake/tests.cmake
+++ b/cmake/tests.cmake
@@ -166,26 +166,9 @@ if(protobuf_BUILD_SHARED_LIBS)
     PRIVATE LIBPROTOBUF_TEST_EXPORTS)
 endif()
 
-add_executable(lite-test
-  ${protobuf_lite_test_files}
-  ${lite_test_util_hdrs}
-  ${lite_test_util_srcs}
-)
-target_link_libraries(lite-test
-  libtest_common_lite
-  ${protobuf_LIB_PROTOBUF_LITE}
-  ${protobuf_ABSL_USED_TARGETS}
-  ${protobuf_ABSL_USED_TEST_TARGETS}
-  GTest::gmock_main
-)
-
-add_test(NAME lite-test
-  COMMAND lite-test ${protobuf_GTEST_ARGS}
-  WORKING_DIRECTORY ${protobuf_SOURCE_DIR})
-
 add_custom_target(full-test
   COMMAND tests
-  DEPENDS tests lite-test fake_plugin test_plugin
+  DEPENDS tests fake_plugin test_plugin
   WORKING_DIRECTORY ${protobuf_SOURCE_DIR})
 
 add_test(NAME full-test
```

**Comment by mkruskal-google** [comment]
FWIW you can set `-Dprotobuf_BUILD_TESTS=OFF` to just not build our tests.  None of these are necessary to *use* protobuf.  We do have tests that set `-fvisibility=hidden`, but I'm just noticing that we only apply it to our libraries, not the tests themselves...

**Comment by JamiKettunen** [comment]
This is still a problem with both [v25.3](https://github.com/protocolbuffers/protobuf/releases/tag/v25.3) and [v26.0-rc3](https://github.com/protocolbuffers/protobuf/releases/tag/v26.0-rc3)

**Comment by JamiKettunen** [comment]
Seems to be fixed with [v27.0-rc1](https://github.com/protocolbuffers/protobuf/releases/tag/v27.0-rc1)
