### ISSUE TITLE
When compiling with gcc9.3.0, I got errors.

### ISSUE THREAD

**Issue by oleotiger** [protocolbuffers/protobuf#8249]
When compiling with gcc9.3.0, I got errors like :
```
In file included from ./google/protobuf/stubs/common.h:46,
                 from ./google/protobuf/stubs/strutil.h:36,
                 from google/protobuf/stubs/strutil.cc:33:
google/protobuf/stubs/strutil.cc: In function 'char* google::protobuf::DoubleToBuffer(double, char*)':
google/protobuf/stubs/strutil.cc:1247:25: error: 'DBL_DIG' was not declared in this scope
 1247 |   GOOGLE_COMPILE_ASSERT(DBL_DIG < 20, DBL_DIG_is_too_big);
      |                         ^~~~~~~
./google/protobuf/stubs/macros.h:115:56: note: in definition of macro 'GOOGLE_COMPILE_ASSERT'
  115 | #define GOOGLE_COMPILE_ASSERT(expr, msg) static_assert(expr, #msg)
      |                                                        ^~~~
google/protobuf/stubs/strutil.cc: In function 'char* google::protobuf::FloatToBuffer(float, char*)':
google/protobuf/stubs/strutil.cc:1365:25: error: 'FLT_DIG' was not declared in this scope
 1365 |   GOOGLE_COMPILE_ASSERT(FLT_DIG < 10, FLT_DIG_is_too_big);
      |                         ^~~~~~~
./google/protobuf/stubs/macros.h:115:56: note: in definition of macro 'GOOGLE_COMPILE_ASSERT'
  115 | #define GOOGLE_COMPILE_ASSERT(expr, msg) static_assert(expr, #msg)
      |                                                        ^~~~
make[2]: *** [google/protobuf/stubs/strutil.lo] Error 1
```

After I roll back to gcc 4.8.5, I can compile protobuf correctly.

**Comment by haberman** [comment]
That is odd.  `strutil.cc` has `#include <float.h>` which should pull in the definition of `DBL_DIG`.

This seems to show `DBL_DIG` as available on GCC 9.3.0: https://godbolt.org/z/8h7ob9

Does the program from that godbolt link compile on your GCC 9.3.0 setup? If not, maybe your setup is busted somehow. If so, perhaps the headers are conflicting with each other in a way that prevents `DBL_DIG` from being defined.
