### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by oldnapalm** [protocolbuffers/protobuf#10075]
Version: 4.21.1
Language: Python
Windows 10
protoc-21.1-win64

Using version 3.20.1 it works, but with 4.21.1 I get `AttributeError: 'NoneType' object has no attribute 'message_types_by_name'`
https://github.com/oldnapalm/zwift-offline/blob/1b3e9d16e903b452d37a77675a38b402abb1e431/protobuf/per_session_info_pb2.py#L22

One difference from this message to others that work is that it has only a repeated field
https://github.com/oldnapalm/zwift-offline/blob/1b3e9d16e903b452d37a77675a38b402abb1e431/protobuf/per-session-info.proto#L9

**Comment by multiplemonomials** [comment]
I saw this on one of my projects too.  In my case, the common factor seems to be that the code ended up importing this particular module (using importlib) twice.  The first time it worked, but the second time it died with that error.

**Comment by oldnapalm** [comment]
A Linux user reported another AttributeError with version 4.21.1 while with 3.20.1 it works.

https://github.com/oldnapalm/zwift-offline/blob/1b3e9d16e903b452d37a77675a38b402abb1e431/zwift_offline.py#L2530

`AttributeError: 'EnumTypeWrapper' object has no attribute 'RealmID'`

https://github.com/oldnapalm/zwift-offline/blob/1b3e9d16e903b452d37a77675a38b402abb1e431/protobuf/udp-node-msgs.proto#L5

**Comment by multiplemonomials** [comment]
Turns out this issue is also happening in a different project here at Relativity, one which does not use importlib and instead just uses a certain arrangement of import statements in a pytest suite.  This one is not workaroundable and we're having to just pin protobuf to 3.x due to this issue.

However, I was able to set up a minimal example of the issue using importlib.  This is able to reproduce reliably on Ubuntu 20 with protoc 3.21 and protobuf python version 4.21.1.

First create foo.proto:
```
syntax = "proto2";

message FooMessage
{
	repeated int32 someInt = 1;
}
```

Then create test.py:
```python
import importlib

for counter in range(0, 2):
	imported_process = importlib.util.spec_from_file_location("foo_pb2", "foo_pb2.py")
	module = importlib.util.module_from_spec(imported_process)
	imported_process.loader.exec_module(module)
```

Then run it:
```
$ python3 test.py
```

This gets:
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    imported_process.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jamie/dev/protobuf-4-bug-repro/foo_pb2.py", line 18, in <module>
    _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
  File "/home/jamie/.local/lib/python3.8/site-packages/google/protobuf/internal/builder.py", line 64, in BuildMessageAndEnumDescriptors
    for (name, msg_des) in file_des.message_types_by_name.items():
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

**Comment by scv119** [comment]
We are running similar issue on Windows. Basically we generated the python files using protobuf 3.19.4 and the using python protobuf package 4.21.1 result into following errors:

```


E                       ray.exceptions.RuntimeEnvSetupError: Failed to setup runtime environment.
--
  | E                       Traceback (most recent call last):
  | E                         File "c:\install\ray\python\ray\dashboard\modules\runtime_env\runtime_env_agent.py", line 412, in _create_runtime_env_with_retry
  | E                           runtime_env_context = await asyncio.wait_for(
  | E                         File "C:\Miniconda3\lib\asyncio\tasks.py", line 494, in wait_for
  | E                           return fut.result()
  | E                         File "c:\install\ray\python\ray\dashboard\modules\runtime_env\runtime_env_agent.py", line 320, in _setup_runtime_env
  | E                           size_bytes = await manager.create(
  | E                         File "c:\install\ray\python\ray\_private\runtime_env\pip.py", line 454, in create
  | E                           return await task
  | E                         File "c:\install\ray\python\ray\_private\runtime_env\pip.py", line 436, in _create_for_hash
  | E                           await PipProcessor(
  | E                         File "c:\install\ray\python\ray\_private\runtime_env\pip.py", line 352, in _run
  | E                           await self._pip_check(
  | E                         File "C:\Miniconda3\lib\contextlib.py", line 178, in __aexit__
  | E                           await self.gen.__anext__()
  | E                         File "c:\install\ray\python\ray\_private\runtime_env\pip.py", line 191, in _check_ray
  | E                           actual_version, actual_path = await _get_ray_version_and_path()
  | E                         File "c:\install\ray\python\ray\_private\runtime_env\pip.py", line 182, in _get_ray_version_and_path
  | E                           output = await check_output_cmd(
  | E                         File "c:\install\ray\python\ray\_private\runtime_env\utils.py", line 101, in check_output_cmd
  | E                           raise SubprocessCalledProcessError(
  | E                       ray._private.runtime_env.utils.SubprocessCalledProcessError: Run cmd[16] failed with the following details.
  | E                       Command '['C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\ray\\session_2022-06-14_22-43-28_070228_8848\\runtime_resources\\pip\\2df5594bf6724cf521fcd471bc903fc6252b3e75\\virtualenv\\Scripts\\python.exe', '-c', 'import ray; print(ray.__version__, ray.__path__[0])']' returned non-zero exit status 1.
  | E                       Last 50 lines of stdout:
  | E                           Traceback (most recent call last):
  | E                             File "<string>", line 1, in <module>
  | E                             File "c:\install\ray\python\ray\__init__.py", line 115, in <module>
  | E                               import ray._raylet  # noqa: E402
  | E                             File "python\ray\_raylet.pyx", line 117, in init ray._raylet
  | E                             File "c:\install\ray\python\ray\exceptions.py", line 7, in <module>
  | E                               from ray.core.generated.common_pb2 import RayException, Language, PYTHON
  | E                             File "c:\install\ray\python\ray\core\generated\common_pb2.py", line 16, in <module>
  | E                               from . import runtime_env_common_pb2 as src_dot_ray_dot_protobuf_dot_runtime__env__common__pb2
  | E                             File "c:\install\ray\python\ray\core\generated\runtime_env_common_pb2.py", line 21, in <module>
  | E                               _PIPRUNTIMEENV = DESCRIPTOR.message_types_by_name['PipRuntimeEnv']
  | E                           AttributeError: 'NoneType' object has no attribute 'message_types_by_name'


```

**Comment by oldnapalm** [comment]
In my case the problem was caused by adding a module directory to sys path and using `import directory.module`. Using `import module` instead, it works with 4.21.1 without issue.

**Comment by iqcqiti** [comment]
Upgrading protobuf fixed this issue for me 
pip install --upgrade protobuf

**Comment by multiplemonomials** [comment]
The example I posted above is still broken with protobuf 4.21.2

**Comment by HiceS** [comment]
I'm experiencing the same issue

using `protoc` version `3.21.2` from homebrew

Tried using pip protobuf packages `4.21.2` and `4.21.1`

I have not had any success using different package import resolution methods.

```
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

Could be because im still running Python 3.9 - seems like there is a soft suggestion that python 3.9 has a specific protoc version linked to it. If anyone knows let me know. There is a brew protobuf target for python3.9. [protobuf brew](https://formulae.brew.sh/formula/protobuf)

**Comment by gnossen** [comment]
An update on this since I ran into this issue while integrating the new Protobuf version with gRPC. The issue seems to be that `AddSerializedFile` will return `None` on subsequent invocations for the same file and same symbol DB. When `None` gets passed to `BuildMessageAndEnumDescriptors`, it has this error.

Since the symbol DB is a process-level singleton, this means that the module-level code of a `_pb2.py` file is executed multiple times within a single process, you'll encounter this error. Normally, this should be fine since modules are cached and subsequent imports of the same `_pb2` will not result in its module-level code being imported.

The issue in _our_ repo was that there was a latent bug in our test runner that imported each _pb2 multiple times under _different names_. By ensuring that each `_pb2` was only imported once under a single module name, this problem was avoided entirely.

**Comment by amenu4aie2** [comment]
> An update on this since I ran into this issue while integrating the new Protobuf version with gRPC. The issue seems to be that `AddSerializedFile` will return `None` on subsequent invocations for the same file and same symbol DB. When `None` gets passed to `BuildMessageAndEnumDescriptors`, it has this error.
> 
> Since the symbol DB is a process-level singleton, this means that the module-level code of a `_pb2.py` file is executed multiple times within a single process, you'll encounter this error. Normally, this should be fine since modules are cached and subsequent imports of the same `_pb2` will not result in its module-level code being imported.
> 
> The issue in _our_ repo was that there was a latent bug in our test runner that imported each _pb2 multiple times under _different names_. By ensuring that each `_pb2` was only imported once under a single module name, this problem was avoided entirely.

how to do this

**Comment by amenu4aie2** [comment]
> An update on this since I ran into this issue while integrating the new Protobuf version with gRPC. The issue seems to be that `AddSerializedFile` will return `None` on subsequent invocations for the same file and same symbol DB. When `None` gets passed to `BuildMessageAndEnumDescriptors`, it has this error.
> 
> Since the symbol DB is a process-level singleton, this means that the module-level code of a `_pb2.py` file is executed multiple times within a single process, you'll encounter this error. Normally, this should be fine since modules are cached and subsequent imports of the same `_pb2` will not result in its module-level code being imported.
> 
> The issue in _our_ repo was that there was a latent bug in our test runner that imported each _pb2 multiple times under _different names_. By ensuring that each `_pb2` was only imported once under a single module name, this problem was avoided entirely.

can you explain or provide the changed files

**Comment by bowenatbear** [comment]
Hey we have run into the similar issue on Ubuntu 16.04 running Python 3.7 and this has been a problem for some time. I had no success using different packages or any other suggested solution.
What we want to do is just to access the `google.cloud.pubsub_v1.types` and we got the error message when we only run the tests for all the import rules.
More details are noted in this ticket: https://github.com/bazelbuild/rules_python/issues/783.
```
from google.cloud import pubsub_v1
  File "/home/me/.cache/bazel/_bazel/xx/sandbox/processwrapper-sandbox/3/execroot/bazel-out/k8-fastbuild/bin/binary_smoke_test.runfiles/deps/pypi__google_cloud_pubsub/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/home/me/.cache/bazel/_bazel/xx/sandbox/processwrapper-sandbox/3/execroot/bazel-out/k8-fastbuild/bin/binary_smoke_test.runfiles/deps/pypi__google_cloud_pubsub/google/cloud/pubsub_v1/types.py", line 26, in <module>
    from google.api import http_pb2  # type: ignore
  File "/home/me/.cache/bazel/_bazel/xx/sandbox/processwrapper-sandbox/3/execroot/bazel-out/k8-fastbuild/bin/binary_smoke_test.runfiles/deps/pypi__googleapis_common_protos/google/api/http_pb2.py", line 36, in <module>
    _HTTP = DESCRIPTOR.message_types_by_name["Http"]
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```
Any suggestion would be appreciated.

**Comment by MattDietz** [comment]
We've been dealing with this for a couple days. There are multiple boxes where we can't reproduce this, and others where I can consistently. So far, the only distinguishing characteristic I can identify is it consistently fails on M1 machines and works x86 based machines.

**Comment by rdayaram31** [comment]
I have the same error as seen below.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [12], in <cell line: 1>()
----> 1 import gmsh

File ~\AppData\Roaming\Python\Python39\site-packages\gmsh.py:53, in <module>
     50     else:
     51         libpath = find_library("gmsh")
---> 53 lib = CDLL(libpath)
     55 try_numpy = True # set this to False to never use numpy
     57 use_numpy = False

File C:\ProgramData\Anaconda3\lib\ctypes\__init__.py:364, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    362 import nt
    363 mode = nt._LOAD_LIBRARY_SEARCH_DEFAULT_DIRS
--> 364 if '/' in name or '\\' in name:
    365     self._name = nt._getfullpathname(self._name)
    366     mode |= nt._LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR

### TypeError: argument of type 'NoneType' is not iterable

help me to overcome this problem.
the first time it works

**Comment by MattDietz** [comment]
I was able to fix our issues by upgrading `grcpio` and adding `grcpio-tools` to our dependencies. Previously, we were only on `grpcio==1.37.1`

```
grpcio==1.47.0
grpcio-tools==1.47.0
```

Installing _just_ `grpcio==1.47.0` caused a separate `free()` on a null pointer, which pointed me to this solution: https://github.com/googleapis/python-pubsub/issues/414

I wanted to understand what had happened, so I dug into the code. In my case, I was running on an M1 Mac. All of our builds were running perfectly fine under our x86-based infra which was the first clue. Looking into the code on version 1.37.1:

https://github.com/protocolbuffers/protobuf/blob/909a0f36a10075c4b4bc70fdee2c7e32dd612a72/python/google/protobuf/descriptor.py#L60-L74
https://github.com/protocolbuffers/protobuf/blob/909a0f36a10075c4b4bc70fdee2c7e32dd612a72/python/google/protobuf/descriptor.py#L966-L985

Note that it attempts to load in extensions. If they aren't present (which they aren't by default under ARM64), you end up with a completely different metaclass for the descriptor.

In our case, we were calling `AddSerializedFile`. In the pure python implementation, there's no `return` which led to our `NoneType` error. https://github.com/protocolbuffers/protobuf/blob/909a0f36a10075c4b4bc70fdee2c7e32dd612a72/python/google/protobuf/descriptor_pool.py#L204-L216

**Comment by CrusKresto** [comment]
As MattDietz mentioned, you need to return in AddSerializedFile function. All you have to do is to write
      
     file_desc =  self._ConvertFileProtoToFileDescriptor(file_desc_proto)
     return file_desc

in  AddSerializedFile function in descriptor_pool.py file

**Comment by helios2k6** [comment]
Yeah, this is absolutely an issue when hit in a Jupyter notebook. We use GRPC to communicate with services in our notebooks and the pb2 file is loaded twice and there's not much we can do about it.

**Comment by gnossen** [comment]
@haberman Can someone on the protobuf team please look into fixing this? While it might not be orthodox to load a single proto into the same process multiple times, it's clearly something that has seeped its way into many people's workflows.

**Comment by haberman** [comment]
Fix is pending in: https://github.com/protocolbuffers/upb/pull/804

**Comment by ericsalo** [comment]
The fix has just been submitted so imma close this.

**Comment by austincollinpena** [comment]
Which release on pip will have this solved?

**Comment by gnossen** [comment]
@haberman @ericsalo Ditto. What is the planned timeline for the release of this patch to PyPi? Reports of affected users continue to roll into the gRPC repo. Is this in the recent 4.21.7 release?

**Comment by RichardLangFromNZ** [comment]
Doesn't seem to be fixed in 4.21.7.  Have just tripped over this setting up a Windows 10 VM with

- python 3.10
- python protobuf 4.21.7 from PyPi
- protoc 21.7 from https://github.com/protocolbuffers/protobuf/releases

**Comment by haberman** [comment]
We are cutting a release shortly that will have the fix. This should land in the next week or so.

**Comment by grainnemcknight** [comment]
@haberman I just upgraded to protobuf (4.21.8) with grpcio & tools (1.50.0) and still getting same error :-(

**Comment by haberman** [comment]
For people who are still seeing the error: are you using pure-Python or the C acceleration (upb)?

What is output if you execute this?

```
$  python -c 'from google.protobuf.internal import api_implementation; print(api_implementation.Type())'
```

My theory is that we fixed this for api implementation type `upb` but it is still broken for api implementation type `python`.

**Comment by deviatormaz** [comment]
> What is output if you execute this?
> 
> ```
> $  python -c 'from google.protobuf.internal import api_implementation; print(api_implementation.Type())'

The two python environments that I'm using the protobufs in both report upb.

**Comment by akhileshraju** [comment]
> What is output if you execute this?
> 
> ```
> $  python -c 'from google.protobuf.internal import api_implementation; print(api_implementation.Type())'
> ```
> 

Same here - both my python envs report `upb` with the latest version

**Comment by haberman** [comment]
It looks like the fix was not included in the release due to a hiccup in the release process.

Sorry about this -- we will be releasing again within the next week and will assure that the fix goes in.

**Comment by mayur-who** [comment]
since this is not yet released, can you please keep this issue open?

**Comment by haberman** [comment]
Sure, re-opening until the fix is released.

**Comment by andre-casimiro** [comment]
Please don't forget this fix :)

**Comment by jayanth86** [comment]
Just wanted to check back in here and see if we're still planning on releasing this fix soon - we're still waiting on this to be fixed so we can update our version and take advantage of the newer features.

**Comment by sknick** [comment]
I'm hitting it too. Seems to be specific to newer Python 3 versions?

**Comment by haberman** [comment]
This was fixed in 4.21.9.

Here is a minimal repro, you can verify it no longer occurs in 4.21.9:

```python
# test.py
from google.protobuf import descriptor_pool as _descriptor_pool

desc1 = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x03\n\x01M')
desc2 = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x03\n\x01M')

print(desc1)
print(desc2)

assert desc1 is not None
assert desc2 is not None
assert desc1 is desc2
```

Demo:

```
$ python -m venv /tmp/venv
$ /tmp/venv/bin/pip install protobuf==4.21.8
[...]
Successfully installed protobuf-4.21.8
$ /tmp/venv/bin/python test.py 
<google._upb._message.FileDescriptor object at 0x7f887c0fbc00>
None
Traceback (most recent call last):
  File "/usr/local/google/home/haberman/test.py", line 10, in <module>
    assert desc2 is not None
AssertionError
$ /tmp/venv/bin/pip install protobuf==4.21.9
[...]
Successfully installed protobuf-4.21.9
$ /tmp/venv/bin/python test.py 
<google._upb._message.FileDescriptor object at 0x7f73b6907c00>
<google._upb._message.FileDescriptor object at 0x7f73b6907c00>
```
