### ISSUE TITLE
xcode-tools v16 breaking protobuf build due to missing cstdint

### ISSUE THREAD

**Issue by JeroenSchmidt** [protocolbuffers/protobuf#18449]
### What version of protobuf and what language are you using?
Workspace:
```
bazel version: 7.3.1
protobuf: protobuf-3.21.12
```

### What operating system (Linux, Windows, ...) and version?
MacOS Sonoma 14.6.1 (M1)

### What runtime / compiler are you using (e.g., python version or gcc version)
```
pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 16.0.0.0.1.1724870825
volume: /
location: /
install-time: 1726557915
```

#### Steps to reproduce the behaviour:
1. Update to xcode-cli tools to `v16.0`
2. `bazel clean --expunge` 
3. Run any bazel target that requires protobuf (e.g. `bazel build //:buildifier`)

#### What did you expect?
For protobuf to be build without an error and my target to run (e.g. `bazel build //:buildifier`)

#### What did you see instead?

When building protobuf the following error is thrown
```
In file included from external/com_google_protobuf/src/google/protobuf/stubs/time.cc:1:
external/com_google_protobuf/src/google/protobuf/stubs/time.h:33:10: fatal error: 'cstdint' file not found
   33 | #include <cstdint>
      |          ^~~~~~~~~
```

#### To resolve this issue:
1. Rollback to xcode-cli tools `v15.3`

This can be obtained from the apple developer portal: ([download link](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_15.3/Command_Line_Tools_for_Xcode_15.3.dmg))

### Full Stack Trace
```
(18:17:42) ERROR: /private/var/tmp/_bazel_MY_USER/6ff7b9f9b6fd27230299938177dc3d1d/external/com_google_protobuf/BUILD.bazel:27:11: Compiling src/google/protobuf/stubs/time.cc [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target @@com_google_protobuf//:protobuf_lite) 
  (cd /private/var/tmp/_bazel_MY_USER/6ff7b9f9b6fd27230299938177dc3d1d/sandbox/darwin-sandbox/3/execroot/__main__ && \
  exec env - \
    PATH=/Users/MY_USER/Library/Caches/bazelisk/downloads/sha256/981f82a470bad1349322b6f51c9c6ffa0aa291dab1014fac411543c12e661dff/bin:/Users/MY_USER/.pyenv/versions/cli-env/bin:/opt/homebrew/Cellar/pyenv/2.4.13/libexec:/opt/homebrew/Cellar/pyenv/2.4.13/plugins/python-build/bin:/Users/MY_USER/.pyenv/shims:/Users/MY_USER/.jenv/shims:/Users/MY_USER/.jenv/bin:/Users/MY_USER/Library/Python/3.9/bin:/Users/MY_USER/.local/bin:/opt/homebrew/opt/openjdk@11/bin:/opt/homebrew/Cellar/apache-spark/3.3.2/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/homebrew/opt/grep/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:/Users/MY_USER/perl5/bin:/Users/MY_USER/perl5/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Privileges.app/Contents/Resources:/usr/local/munki \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++14' -MD -MF bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/com_google_protobuf/_objs/protobuf_lite/time.d '-frandom-seed=bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/com_google_protobuf/_objs/protobuf_lite/time.o' -iquote external/com_google_protobuf -iquote bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/com_google_protobuf -isystem external/com_google_protobuf/src -isystem bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/com_google_protobuf/src '-mmacosx-version-min=10.11' -g0 -g0 -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/stubs/time.cc -o bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/com_google_protobuf/_objs/protobuf_lite/time.o)
# Configuration: f0dd80b0336242eceb76a976365fe987943b0da6360b426b09a229bc9b83546e
# Execution platform: @@internal_platforms_do_not_use//host:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/com_google_protobuf/src/google/protobuf/stubs/time.cc:1:
external/com_google_protobuf/src/google/protobuf/stubs/time.h:33:10: fatal error: 'cstdint' file not found
   33 | #include <cstdint>
      |          ^~~~~~~~~
1 error generated.
Target @@com_github_bazelbuild_buildtools//buildozer:buildozer failed to build
```

**Comment by develar** [comment]
Yes, I also cannot build my java project using Bazel after update to v16.

**Comment by acozzette** [comment]
Do you have any sense of why the `cstdint` header isn't available with xcode 16?

We could perhaps try to work around the issue by using `stdint.h` instead, but we would be likely to break it again by accident.

**Comment by acozzette** [comment]
Actually protobuf 3.21 is also old enough to be outside our support window (see [here](https://protobuf.dev/support/version-support/)). Are you able to reproduce the problem with a newer supported version?

**Comment by JeroenSchmidt** [comment]
Hi @acozzette 
We were able to around this problem by just using the prebuilt builderfier (thus not needing to build protobuff)
```
bazel_dep(name = "buildifier_prebuilt", version = "7.3.1")
```

At the time we were using the `protobuf-3.21.12` because of the cross dependency requirements from the buildifier version we depended on.

**Comment by acozzette** [comment]
Great, as long as you have a workaround then I will go ahead and close this. We can reopen it if we find that it affects more recent versions.
