### ISSUE TITLE
CMakeLists.txt using C++ standard 11 which is not sufficient for v3.21.12?

### ISSUE THREAD

**Issue by MichaelVoelkel** [protocolbuffers/protobuf#11469]
**What version of protobuf and what language are you using?**
Version: v3.21.12
Language: C++

**What operating system (Linux, Windows, ...) and version?**
macOS13

**What runtime / compiler are you using (e.g., python version or gcc version)**
Standard is Ninja generator and in turn clang++ is used.

**What did you do?**
1. Checkout this repository
2. `mkdir build`
3. `cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON
4. `cmake --build . --config Release`

**What did you expect to see**
It working.

**What did you see instead?**
Various compiler errors that are related to C++ being only on std11.

**Anything else we should know about your project / environment**
If I change `CMakeLists.txt` setting the C++ standard to C++17 it works (14 probably too, not checked right now).

**Comment by devjgm** [comment]
@MichaelVoelkel Can you please clarify exactly which version of protobuf you're using? I just tried your steps with version 3.21.12 (https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-all-21.12.tar.gz) on macOS 13.1 (which may be different than your step 1), and the build worked.

Can you also include a snippet of the error you saw?

**Comment by MichaelVoelkel** [comment]
Hi!

Sure, let me provide more details.

So, `git log -n1` shows:
```
commit f0dc78d7e6e331b8c6bb2d5283e06aa26883ca7c (HEAD, tag: v3.21.12, tag: v21.12)
```

Ninja build then says (as for exact compiler):
```
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

One error is then:
```
FAILED: CMakeFiles/gmock.dir/third_party/googletest/googlemock/src/gmock-all.cc.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_ZLIB -I/Users/michael/Private/myProject/build/protobuf -I/Users/michael/Private/myProject/libs/protobuf/src -I/Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googlemock -I/Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googletest -I/Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googletest/include -I/Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googlemock/include -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -fPIC -std=c++11 -MD -MT CMakeFiles/gmock.dir/third_party/googletest/googlemock/src/gmock-all.cc.o -MF CMakeFiles/gmock.dir/third_party/googletest/googlemock/src/gmock-all.cc.o.d -o CMakeFiles/gmock.dir/third_party/googletest/googlemock/src/gmock-all.cc.o -c /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googlemock/src/gmock-all.cc
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googlemock/src/gmock-all.cc:39:
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googlemock/include/gmock/gmock.h:56:
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googlemock/include/gmock/gmock-actions.h:145:
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:50:
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googletest/include/gtest/gtest.h:60:
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googletest/include/gtest/gtest-death-test.h:43:
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h:46:
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googletest/include/gtest/gtest-matchers.h:48:
In file included from /Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googletest/include/gtest/gtest-printers.h:114:
/Users/michael/Private/myProject/libs/protobuf/third_party/googletest/googletest/include/gtest/internal/gtest-internal.h:635:54: error: too few template arguments for class template 'less'
  typedef ::std::map<std::string, CodeLocation, std::less<>> RegisteredTestsMap;
```

**Comment by devjgm** [comment]
Oh, that's an error from Googletest. _Googletest_ no longer supports C++11. If you avoid building our tests, Protobuf should all work fine in C++11 mode (for the 3.21.12 version, that is).

**Comment by MichaelVoelkel** [comment]
Indeed, that solves it! But it should be possible to also build tests, no? :) Os is `CMakeLists.txt` not actively maintained?

**Comment by devjgm** [comment]
> But it should be possible to also build tests, no? :) Os is `CMakeLists.txt` not actively maintained?

We do actively support and maintain `CMakeLists.txt`, but we do not test nor guarantee that it works for _development_ in our repo. For development, we only officially support `bazel`. But for _releases_, we do officially support CMake.

However, if you want to build directly from the repo with cmake, it _should_ work if you specify `cmake -DCMAKE_CXX_STANDARD=17 ...` (or 14) in your configure step.

Hope that helps, or at least clears up the confusion. Re-open the issue if there's more.
