### PR TITLE
Adding full build to 32 bit tests

### LINKED ISSUE #9573: [MSVC] When building Google_Protobuf emits error C2338 on MSVC
Hi, all
Google_Protobuf fails to build on MSVC build main_20220223.01 due to error C2338. Could you please help look at this issue? Thank you very much.

**What version of protobuf and what language are you using?**
Version: 29b3d01

**What operating system (Linux, Windows, ...) and version?**
Window 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
git 

**What did you do?**
1. open VS2019 x64 tools command
2. git clone https://github.com/google/protobuf F:\gitP\google\protobuf\build_x86
3. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
4. set originalLIB=%_LIB_%
5. set _LIB_=/MACHINE:X86 %orignalLIB%
6. cd F:\gitP\google\protobuf\build_x86
7. msbuild /p:Platform=Win32 /p:Configuration=Release protobuf.sln /t:Rebuild 2>&1

**What did you expect to see**
Compile fine.
**What did you see instead?**
F:\gitP\google\protobuf\src\google/protobuf/repeated_field.h(81,27): error C2338: static_assert failed: '' (compiling source file F:\gitP\google\protobuf\src\google\protobuf\extension_set_unittest.cc) [F:\gitP\google\protobuf\build_x86\tests.vcxproj]
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Build log**

[Google build.txt](https://github.com/protocolbuffers/protobuf/files/8175871/Google.build.txt)

### LINKED ISSUE #10418: Build Fails on 32-Bit ARM
A `static_assert` is failing when building for 32-bit ARM.

**Build Error:**
```
In file included from /protobuf/src/google/protobuf/implicit_weak_message.h:39,
                 from /protobuf/src/google/protobuf/generated_message_util.h:54,
                 from /protobuf/src/google/protobuf/generated_message_bases.h:40,
                 from /protobuf/src/google/protobuf/unittest.pb.h:26,
                 from /protobuf/src/google/protobuf/extension_set_unittest.cc:39:
/protobuf/src/google/protobuf/repeated_field.h: In instantiation of 'constexpr int google::protobuf::internal::RepeatedFieldLowerClampLimit() [with T = long long int; int kRepHeaderSize = 4]':
/protobuf/src/google/protobuf/extension_set_unittest.cc:871:3:   required from here
/protobuf/src/google/protobuf/repeated_field.h:81:27: error: static assertion failed
   81 |   static_assert(sizeof(T) <= kRepHeaderSize, "");
```

**Offending static_assert:**
`src/google/protobuf/repeated_field.h:81`
```
template <typename T, int kRepHeaderSize>
constexpr int RepeatedFieldLowerClampLimit() {
  // The header is padded to be at least `sizeof(T)` when it would be smaller
  // otherwise.
  static_assert(sizeof(T) <= kRepHeaderSize, "");
```

**What version of protobuf and what language are you using?**
Verified to fail on both v21.5 and main (commit 2b673bb)

**What operating system:** Ubuntu Jammy

**What runtime / compiler**
The build fails with both:
- Ubuntu Jammy's GCC 11.2 native armhf compiler
- Ubuntu Jammy's GCC 11.2 armhf cross-compiler

**What did you do?**

Here’s a Dockerfile file that reproduce the build error using cross-compilation. 
1. Copy the following into a file named Dockerfile in an empty directory
2. Run with: `docker build .`
```Dockerfile
FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -yq update
RUN apt-get -yq install apt-utils
RUN apt-get -yq install ninja-build git cmake build-essential gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

RUN git clone --depth 1 --recurse-submodules --single-branch https://github.com/protocolbuffers/protobuf.git

WORKDIR /protobuf

# Build and install native protoc
RUN cmake -GNinja .
RUN ninja install
RUN git clean -ffxd


# Cross compile to armhf
ENV CC=arm-linux-gnueabihf-gcc
ENV CXX=arm-linux-gnueabihf-g++

RUN cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=arm -GNinja .

# Build offending target. Remove argument to verify full build
RUN ninja CMakeFiles/tests.dir/src/google/protobuf/extension_set_unittest.cc.o
```

### PR DESCRIPTION
**Pull request by mkruskal-google**
Closes #10418
Closed #9573

### CODE REVIEW

**Review by sbenzaquen — APPROVED** [review]

**Comment by Apteryks** [comment]
OK, with a comrade we've now isolated the problem to the C++ standard used.  In the last release it was still 11 but the i686 patch requires C++ 14.
