### ISSUE TITLE
Java compile version issue when upgrading to 3.12.4

### ISSUE THREAD

**Issue by kolea2** [protocolbuffers/protobuf#7827]
**What version of protobuf and what language are you using?**
Version: protobuf-java 3.12.4
Language: Java

**What did you do?**

When executing this line of code (https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/scanner/ReadRowsAcceptanceTest.java#L184), we are seeing this error message:
```
[ERROR] test[twoRowsEmptyValue](com.google.cloud.bigtable.grpc.scanner.ReadRowsAcceptanceTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
	at com.google.protobuf.TextFormat$Parser.toStringBuilder(TextFormat.java:1686)
	at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1670)
	at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1642)
	at com.google.protobuf.TextFormat.merge(TextFormat.java:1448)
	at com.google.cloud.bigtable.grpc.scanner.ReadRowsAcceptanceTest.addResponses(ReadRowsAcceptanceTest.java:184)
	at com.google.cloud.bigtable.grpc.scanner.ReadRowsAcceptanceTest.test(ReadRowsAcceptanceTest.java:173)
```

This started when upgrading from protobuf-java 3.12.2 to 3.12.4. I can confirm that testing locally, the test fails with a Java 8 build and passes with Java 11 (`CharBuffer.flip()` changed between those two versions of java). Were there any changes to the language compile level in protobuf-java recently that would explain this?

Thanks for your help!

**Comment by suztomo** [comment]
I'm able to reproduce the issue in a simple Maven project https://github.com/suztomo/protobuf-i7827.

**Comment by cpovirk** [comment]
It sounds like the linkage checker may soon help detect this, but FYI, another option is to run Animal Sniffer, as [we do in Guava](https://github.com/google/guava/blob/d8e921fd2df52184708d6eb9516e4869f548d841/pom.xml#L139-L160).

I've heard mixed things about the `--release` flag. It may be simplest to just build with JDK8. But as long as Animal Sniffer or an updated linkage checker is in place, I would assume that anything that works is fine.

If you want to avoid this particular error without changing compiler settings, you may be able to change [the code](https://github.com/protocolbuffers/protobuf/blob/v3.12.4/java/core/src/main/java/com/google/protobuf/TextFormat.java#L1686) to upcast the buffer to `Buffer` before calling `flip()`. Maybe I'll put together a fix.

**Comment by cpovirk** [comment]
Uh-oh:

- Animal Sniffer detects this, and it _logs_, but it does not report an _error_:
    - https://github.com/mojohaus/animal-sniffer/issues/77
    - https://github.com/mojohaus/animal-sniffer/pull/83
    - https://github.com/mojohaus/animal-sniffer/pull/87
- The signature changes affect _dozens_ of calls in protobuf. So while we _could_ cast to `Buffer` before every call (or maybe change the types of some fields/variables/parameters), it would be a pain, and without an automated check, it would likely regress.

`--release 8` (or just building with JDK 8, which [maven-enforcer-plugin can require](https://maven.apache.org/enforcer/maven-enforcer-plugin/usage.html)) sounds potentially more promising.

(I assume you're building releases with Maven, but I see some (Bazel) BUILD files, too, so it's possible that I'm wrong about that.)

**Comment by cpovirk** [comment]
Oh, and I had trouble building _anything_ with Maven with JDK11+ because of a maven-surefire-plugin problem with `SystemUtils.isJavaVersionAtLeast` in recent versions of Java. It's probably fixable by upgrading maven-surefire-plugin and/or some of its libraries.

It's possible that `-DskipTests` would at least let you get far enough to see the non-fatal Animal Sniffer messages. If not, another hacky workaround (not to be committed) is to stick this in the parent's pluginManagement:

```xml
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <executions>
            <execution>
              <id>default-test</id>
              <phase />
            </execution>
          </executions>
        </plugin>
```

**Comment by cpovirk** [comment]
It sounds like the right solution here is to pass `--release` to javac (by setting `<release>` for maven-compiler-plugin).

The pom.xml suggests that you're actually targeting Java _7_, not 8, so that would be `<release>7</release>`, replacing [the existing `<source>` and `<target>`](https://github.com/protocolbuffers/protobuf/blob/7db720e07524f96be558f194ae1ffee4a9d49972/java/pom.xml#L120-L121).

The downside to that is that you need to require that developers who build protobuf themselves build with [JDK 9+ to use `--release`](https://openjdk.java.net/jeps/247). You could hide the `<release>` setting behind a `<profile>` so that you can disable it for JDK 8, but that just means that, when you build with JDK 8, you still won't have a strong guarantee of compatibility with Java 7. (That risk might be tolerable, but it also seems easy enough to avoid.)

**Comment by cpovirk** [comment]
Ah, but `--release` prevents usage of `Unsafe`.

I then tried:

`<compilerArgs><arg>--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED</arg></compilerArgs>`

But:

`error: option --add-exports not allowed with target 1.7`

(nor with target 1.8, so (a) you can't just bump to that (even if you wanted to) and (b) this doesn't help us [for Guava](https://github.com/google/guava/issues/3990), either)

The only truly correct solution may be to build with Java 7 (or at least with Java 8 pointed at a Java 7 bootclasspath). Animal Sniffer can help somewhat, but the fact that it [doesn't actually fail the build](https://github.com/protocolbuffers/protobuf/issues/7827#issuecomment-676563016) is unfortunate. Maybe the best bet is a combination of (a) requiring building with Java 8 and (b) asking Animal Sniffer to look for compatibility with Java 7?

**Comment by cpovirk** [comment]
Err, I may have actually seen some evidence that Animal Sniffer's signatures for Java 7 _likewise_ reject usage of `Unsafe`? If so, I was hoping that there was a set of signatures for `java17-sun`, but [it appears not](https://repo1.maven.org/maven2/org/codehaus/mojo/signature/). (Oddly, the `java18` set of signatures that [we use for Guava](https://github.com/google/guava/blob/23be71af402328c19e00c333e370e31357308b4b/pom.xml#L147) _permits_ `Unsafe`.)

So, if you want to use Animal Sniffer, you'll probably have to mark your `Unsafe`-using code with Animal Sniffer's `@IgnoreJRERequirement` annotation (or [a custom annotation you configure to avoid that dependency](https://github.com/google/guava/commit/5f37e53fd73540acdc1d69e33ecc8a91827890a7#diff-600376dffeb79835ede4a0b285078036)).

Supposedly you can generate your own signatures for the JDK or anything else, but that sounds like a pain.

**Comment by TeBoring** [comment]
Would dropping support for java7 and using ```--release 8``` fix the issue?

**Comment by cpovirk** [comment]
It would, but `--release` doesn't let us use `Unsafe`. I didn't look at how protobuf uses it; I just saw that it used it somewhere.

**Comment by TeBoring** [comment]
I saw you mentioned cast to ```Buffer``` before every call. How many places need to change? Does that also work?

**Comment by cpovirk** [comment]
Yes, upcasting to `Buffer` before every call would work. I believe I saw a couple dozen calls, but I don't remember offhand. I'll see if I can look that up quickly.

**Comment by cpovirk** [comment]
Here's an attempt to identify affected calls (excluding tests): [covariants.txt](https://github.com/protocolbuffers/protobuf/files/5130396/covariants.txt)

That's 60 calls -- more than I'd remembered.

**Comment by TeBoring** [comment]
Just replace all of them seems feasible

**Comment by TeBoring** [comment]
BTW, internally we are using java8, why this didn't fail internally?

**Comment by cpovirk** [comment]
Internally, we build against a Java 8 bootclasspath. It's a lot like building with `--release` (except that it lets us use `Unsafe`).

**Comment by TeBoring** [comment]
How does ```--release``` reject ```Unsafe```? A build error? Or only happens with Animal Sniffer?
If so, can we use ```--release``` without Animal Sniffer?

**Comment by cpovirk** [comment]
It produces a javac build error, so it's a problem even without Animal Sniffer.

I have wondered if we could find a workaround (like putting Unsafe on the classpath), but I haven't experimented.

**Comment by TeBoring** [comment]
Can you point out to me where are those ```Unsafe```?
And what are the suggest replacement for them?

**Comment by cpovirk** [comment]
I see 2 files that use `Unsafe:
- https://github.com/protocolbuffers/protobuf/blob/70b02861f8e8ba711efd187188dfb930db7bcaba/java/core/src/main/java/com/google/protobuf/MessageSchema.java#L102
- https://github.com/protocolbuffers/protobuf/blob/70b02861f8e8ba711efd187188dfb930db7bcaba/java/core/src/main/java/com/google/protobuf/UnsafeUtil.java#L45

If you want maximum performance, there is no replacement for them when targeting Java 7 or Java 8 :(

(Under Java 9+, you could probably use [`VarHandle`](https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/VarHandle.html) for at least some of your usages. I don't know if if covers them all. If not, Java has gradually added more replacements for `Unsafe` APIs.)

**Comment by TeBoring** [comment]
Then, for now, seems either do the casting for Buffer or adding Unsafe to
classpath (assuming our change could cover our user, please confirm)

**Comment by cpovirk** [comment]
I believe that either of (a) casting to `Buffer` or (b) building with `--release 7` and `Unsafe` on the classpath is enough to solve the problem for users, yes.

And it looks like you can indeed manually put `Unsafe` on the classpath when you use `--release 7`. There's a copy in `$JAVA_HOME/lib/ct.sym` under `/9A/sun/misc/Unsafe.sig`. We'd need to:
- unzip/unjar that somewhere
- move+rename it to have path `sun/misc/Unsafe.class`
- add that to the classpath

**Comment by kolea2** [comment]
Thank you all for the detailed analysis on the issue. I think casting to `Buffer` would solve the issue at hand as well, though I'd worry there are similar issues that we have not yet come across. I'd also like to understand what changed between 3.12.2 and 3.12.4 that initially broke this?

**Comment by cpovirk** [comment]
Probably 3.12.2 was built with JDK 8 but 3.12.4 was built with JDK 11.

The good news is that [`Buffer` might be the only common API affected](https://github.com/protocolbuffers/protobuf/issues/7827#issuecomment-678351874).

**Comment by TeBoring** [comment]
@cpovirk you mean our maven released jar is built with jdk 11 for 3.12.4, but was jdk 8 for 3.12.2?

**Comment by cpovirk** [comment]
Right. The default JDK installed on Google workstations changed from 8 to 11 on June 23.

**Comment by TeBoring** [comment]
Is there any internal flag we can switch to jdk8?

**Comment by cpovirk** [comment]
You can set `$JAVA_HOME`, as in:

```
$ JAVA_HOME=/usr/local/buildtools/java/jdk8 mvn clean install
```

**Comment by elharo** [comment]
What's the build and release process for this library? Is it being built on an individual developer workstation with `mvn perform:release` or equivalent? If so, we might want to switch to kokoro+Rapid for multiple reasons.

**Comment by TeBoring** [comment]
I think it’s kokoro + docker

**Comment by TeBoring** [comment]
Sent a fix internally for our release process. Seems we are using the default ```/usr/local/buildtools/java/jdk```.

**Comment by elharo** [comment]
@Teboring can you point me to the internal changes you made?

@suztomo we should audit the various release scripts and kokoro configs in google3 to check whether they explicitly specify a JDK. java 8 or Java 11, this should be a  deliberate choice, not an  accident.

**Comment by cpovirk** [comment]
@elharo: I just CCed you. (If it's not showing up, search for the URL of this issue.)

Good point about the search. A search like `/usr/local/buildtools/java/jdk\b -f:/usr/local/buildtools/java/jdk f:(release|kokoro)` turns up at least a couple suspicious files -- one that has the release instructions for [libphonenumber](https://github.com/google/libphonenumber) and one that sets up the `PATH` to contain `/usr/local/buildtools/java/jdk/bin` for probably _many_ release processes. I'm going to raise this on an internal issue, on which I'll also CC you.

**Comment by suztomo** [comment]
@TeBoring Hi Paul, do you have plan to release a fix to this issue?

**Comment by eed3si9n** [comment]
I came to report that I ran into a similar issue. Different method from op but one that's listed in [convariants.txt](https://github.com/protocolbuffers/protobuf/files/5130396/covariants.txt) so I guess you're aware of it:

```
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
  at com.google.protobuf.NioByteString.copyToInternal(NioByteString.java:112)
  at com.google.protobuf.ByteString.toByteArray(ByteString.java:695)
  at com.google.protobuf.NioByteString.writeTo(NioByteString.java:123)
  at org.apache.beam.sdk.extensions.protobuf.ByteStringCoder.encode(ByteStringCoder.java:67)
  at org.apache.beam.sdk.extensions.protobuf.ByteStringCoder.encode(ByteStringCoder.java:37)
  at org.apache.beam.sdk.coders.DelegateCoder.encode(DelegateCoder.java:74)
  at org.apache.beam.sdk.coders.DelegateCoder.encode(DelegateCoder.java:68)
```

In general, does this prevent people/companies from using protobuf 3.12.4+ if they are on JDK < 10? If I understand correctly, these would sometimes show up as a runtime error, like in this case you could be calling a method on Apache Beam. If so it might be helpful if this issue was hi-lighted better the release note as a known issue.

**Comment by eed3si9n** [comment]
> Not necessarily. It just means that the Protobuf Java developers have to arrange for the `protobuf-java` library to get built in a way that will make it work on all the supported Java versions. They can do that right now, but they haven't done it yet. 

I understand that at some point in the future this may be fixed. What I'm saying is that today, if any of the Java/Scala etc libraries pulled in 3.12.4+ (because why not?) it could result to a runtime error in a production system. Thankfully my work code had a decent code coverage, so we caught this, but not everyone might. So I'm asking this issue be highlighted in the release note of 3.12.4, 3.13.0, and 3.13.0.1 as a known regression with regard to JDK 8.

**Comment by suztomo** [comment]
Beam's protobuf dependency hit this.
https://lists.apache.org/thread.html/r1387b34ec5995c87f079cb41e8f62096f83ed350b8378bd6389416e6%40%3Cdev.beam.apache.org%3E

**Comment by iemejia** [comment]
Is this fixed in 3.14.0 ?

**Comment by suztomo** [comment]
I see it's fixed in 3.14.0. Thank you.

**Comment by ijuma** [comment]
Fyi, we use `--release 8` and `Unsafe` in Kafka and it works. Perhaps the issue you mentioned only happens if the module path is used.

**Comment by cpovirk** [comment]
Thanks. It looks like the difference is that you never refer directly to the type `Unsafe`, only through reflection. We are probably avoiding that for performance reasons, but I see that you can use `MethodHandle` to optimize. (I may have forgotten that `MethodHandle` is available as far back as... Java 7?)

**Comment by ijuma** [comment]
Oh, I see. Method handles are available since Java 7, but Android is a bit of a problem.
