### ISSUE TITLE
PHP extension don't build with PHP 8.1

### ISSUE THREAD

**Issue by remicollet** [protocolbuffers/protobuf#8711]
```
/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS/array.c: In function 'Array_ModuleInit':
/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS/array.c:643:55: error: 'spl_ce_ArrayAccess' undeclared (first use in this function); did you mean 'zend_ce_arrayaccess'?
  643 |   zend_class_implements(RepeatedField_class_entry, 3, spl_ce_ArrayAccess,
      |                                                       ^~~~~~~~~~~~~~~~~~
      |                                                       zend_ce_arrayaccess
/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS/array.c:643:55: note: each undeclared identifier is reported only once for each function it appears in
/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS/array.c:644:44: error: 'spl_ce_Countable' undeclared (first use in this function); did you mean 'zend_ce_countable'?
  644 |                         zend_ce_aggregate, spl_ce_Countable);
      |                                            ^~~~~~~~~~~~~~~~
      |                                            zend_ce_countable
make[1]: *** [Makefile:203: array.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS/map.c: In function 'Map_ModuleInit':
/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS/map.c:639:50: error: 'spl_ce_ArrayAccess' undeclared (first use in this function); did you mean 'zend_ce_arrayaccess'?
  639 |   zend_class_implements(MapField_class_entry, 3, spl_ce_ArrayAccess,
      |                                                  ^~~~~~~~~~~~~~~~~~
      |                                                  zend_ce_arrayaccess
/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS/map.c:639:50: note: each undeclared identifier is reported only once for each function it appears in
/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS/map.c:640:44: error: 'spl_ce_Countable' undeclared (first use in this function); did you mean 'zend_ce_countable'?
  640 |                         zend_ce_aggregate, spl_ce_Countable);
      |                                            ^~~~~~~~~~~~~~~~
      |                                            zend_ce_countable
make[1]: *** [Makefile:212: map.lo] Error 1
make[1]: Leaving directory '/dev/shm/BUILD/php81-php-pecl-protobuf-3.17.3/NTS'

```

**Comment by remicollet** [comment]
Possible fix see #8710

**Comment by remicollet** [comment]
Yes: 

* `spl_ce_ArrayAccess`  is an alias of `zend_ce_arrayaccess` since PHP 5.1
* `spl_ce_Countable`  is an alias of   `zend_ce_countable` since PHP 7.2

These alias have only be removed, as new name should be used for a lot time (no dependency on spl extension)
