### ISSUE TITLE
[Build] Failure to build with "expected identifier before ‘alignas’`"

### ISSUE THREAD

**Issue by veblush** [protocolbuffers/protobuf#16867]
**What version of protobuf and what language are you using?**

Protobuf commit [9f40411](https://github.com/protocolbuffers/protobuf/commit/9f40411caf070c2848281a507529e4f5506dc22d)

**What operating system (Linux, Windows, ...) and version?**

Linux Debian 11 using Docker 

**What runtime / compiler are you using (e.g., python version or gcc version)**

gcc 10 / cmake build with `-DBUILD_SHARED_LIBS=ON`

**What did you do?**

Build protobuf with cmake `-DBUILD_SHARED_LIBS=ON` option

**What did you expect to see**

Successful build

**What did you see instead?**

Build failure with [log](https://btx.cloud.google.com/invocations/d5c066c7-725c-4452-bbf8-e1f03e8b7f14/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_bloat_diff;config=default/log)

```
[ 36%] Building CXX object third_party/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/any.cc.o
In file included from /var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/any.pb.h:21,
                 from /var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/any.pb.cc:6:
/var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/arena.h:145:23: error: expected identifier before ‘alignas’
  145 | class PROTOBUF_EXPORT alignas(8) Arena final {
      |                       ^~~~~~~
/var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/arena.h:145:40: error: expected initializer before ‘final’
  145 | class PROTOBUF_EXPORT alignas(8) Arena final {
      |                                        ^~~~~
/var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/arena.h:659:61: error: invalid use of incomplete type ‘class google::protobuf::Arena’
  659 | PROTOBUF_NOINLINE void* Arena::DefaultConstruct(Arena* arena) {
      |                                                             ^
/var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/arena.h:51:7: note: forward declaration of ‘class google::protobuf::Arena’
   51 | class Arena;    // defined below
      |       ^~~~~
/var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/arena.h:667:76: error: invalid use of incomplete type ‘class google::protobuf::Arena’
  667 | PROTOBUF_NOINLINE void* Arena::CopyConstruct(Arena* arena, const void* from) {
      |                                                                            ^
/var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/arena.h:51:7: note: forward declaration of ‘class google::protobuf::Arena’
   51 | class Arena;    // defined below
      |       ^~~~~
/var/local/jenkins/grpc/third_party/protobuf/src/google/protobuf/arena.h:675:37: error: expected initializer before ‘<’ token
  675 | inline void* Arena::AllocateInternal() {
```
**Anything else we should know about your project / environment**

- You can check the PR catching this issue; https://github.com/grpc/grpc/pull/36626
- This test is running under this docker image; `us-docker.pkg.dev/grpc-testing/testing-images-public/cxx_debian11_x64:a9c5d062364adc836b4068cad93a3e448b25c37c@sha256:9f9285da21c1053ac715027e0cee66c20c70ebf016053328a4cee61ffd37e59b`

**Comment by zhangskz** [comment]
@sbenzaquen Looks like this was introduced in https://github.com/protocolbuffers/protobuf/commit/ec126a5069fbb81a857e41c8b2cfbe71ace35993, which undoes previous fix for this https://github.com/protocolbuffers/protobuf/commit/32caf511c8. Can you take a look?

**Comment by veblush** [comment]
Verified and thanks for the quick fix. This issue can be closed if there is nothing to follow up with.

**Comment by zhangskz** [comment]
Thanks for confirming -- closing.

This was fixed via rollback: https://github.com/protocolbuffers/protobuf/commit/baeab50df02ce0c7b5926f0263ea8857871e91de
